// AUTO-GENERATED from the platforms table. Idempotent seed source.
// Regenerate after platform catalog changes; run via `pnpm --filter @workspace/db run seed`.
import type { InsertPlatform } from "./schema";

export const platformSeed: InsertPlatform[] = [
  {
    "name": "WhatsApp",
    "slug": "whatsapp",
    "url": "https://web.whatsapp.com",
    "category": "Messaging",
    "color": "#25D366",
    "description": "World's most popular messaging app",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Telegram",
    "slug": "telegram",
    "url": "https://web.telegram.org",
    "category": "Messaging",
    "color": "#229ED9",
    "description": "Fast, secure, cloud-based messaging",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Facebook Messenger",
    "slug": "facebook-messenger",
    "url": "https://www.messenger.com",
    "category": "Messaging",
    "color": "#0084FF",
    "description": "Facebook's messaging platform",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Discord",
    "slug": "discord",
    "url": "https://discord.com/app",
    "category": "Communities",
    "color": "#5865F2",
    "description": "Voice, video & text for communities",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Slack",
    "slug": "slack",
    "url": "https://app.slack.com",
    "category": "Work",
    "color": "#4A154B",
    "description": "Team collaboration and messaging",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Microsoft Teams",
    "slug": "microsoft-teams",
    "url": "https://teams.microsoft.com",
    "category": "Work",
    "color": "#6264A7",
    "description": "Microsoft's team collaboration hub",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Instagram DMs",
    "slug": "instagram",
    "url": "https://www.instagram.com/direct/inbox",
    "category": "Social",
    "color": "#E1306C",
    "description": "Instagram direct messages",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Twitter / X",
    "slug": "twitter",
    "url": "https://twitter.com/messages",
    "category": "Social",
    "color": "#1DA1F2",
    "description": "Twitter direct messages and chat",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "LinkedIn",
    "slug": "linkedin",
    "url": "https://www.linkedin.com/messaging",
    "category": "Social",
    "color": "#0A66C2",
    "description": "Professional networking messages",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Reddit Chat",
    "slug": "reddit",
    "url": "https://www.reddit.com/message/inbox",
    "category": "Social",
    "color": "#FF4500",
    "description": "Reddit messages and chat",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Gmail",
    "slug": "gmail",
    "url": "https://mail.google.com",
    "category": "Email",
    "color": "#EA4335",
    "description": "Google's email platform",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "ProtonMail",
    "slug": "protonmail",
    "url": "https://mail.proton.me",
    "category": "Email",
    "color": "#6D4AFF",
    "description": "End-to-end encrypted email",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Outlook",
    "slug": "outlook",
    "url": "https://outlook.live.com",
    "category": "Email",
    "color": "#0078D4",
    "description": "Microsoft email and calendar",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Signal",
    "slug": "signal",
    "url": "https://signal.org/download",
    "category": "Privacy",
    "color": "#3A76F0",
    "description": "Private, encrypted messaging",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Threema",
    "slug": "threema",
    "url": "https://web.threema.ch",
    "category": "Privacy",
    "color": "#3F9E4A",
    "description": "Anonymous & secure messaging",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Wire",
    "slug": "wire",
    "url": "https://app.wire.com",
    "category": "Privacy",
    "color": "#000000",
    "description": "Secure team collaboration",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Keybase",
    "slug": "keybase",
    "url": "https://keybase.io",
    "category": "Privacy",
    "color": "#FF6F21",
    "description": "Encrypted messaging with keys",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Google Meet",
    "slug": "google-meet",
    "url": "https://meet.google.com",
    "category": "Video",
    "color": "#00AC47",
    "description": "Google video conferencing",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Zoom",
    "slug": "zoom",
    "url": "https://app.zoom.us",
    "category": "Video",
    "color": "#2D8CFF",
    "description": "Video meetings and webinars",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Notion",
    "slug": "notion",
    "url": "https://www.notion.so",
    "category": "Work",
    "color": "#000000",
    "description": "All-in-one workspace",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Basecamp",
    "slug": "basecamp",
    "url": "https://basecamp.com",
    "category": "Work",
    "color": "#1D2D35",
    "description": "Project management & messaging",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Mattermost",
    "slug": "mattermost",
    "url": "https://mattermost.com",
    "category": "Work",
    "color": "#0057CC",
    "description": "Open-source team messaging",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Rocket.Chat",
    "slug": "rocket-chat",
    "url": "https://open.rocket.chat",
    "category": "Work",
    "color": "#F5455C",
    "description": "Open-source team communication",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Flock",
    "slug": "flock",
    "url": "https://app.flock.com",
    "category": "Work",
    "color": "#6C63FF",
    "description": "Team messaging and collaboration",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Zulip",
    "slug": "zulip",
    "url": "https://zulip.com",
    "category": "Work",
    "color": "#206EA6",
    "description": "Organized team chat",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Flowdock",
    "slug": "flowdock",
    "url": "https://app.flowdock.com",
    "category": "Work",
    "color": "#04A664",
    "description": "Team inbox and chat",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "WeChat",
    "slug": "wechat",
    "url": "https://web.wechat.com",
    "category": "Messaging",
    "color": "#07C160",
    "description": "China's leading super-app",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Line",
    "slug": "line",
    "url": "https://line.me/en",
    "category": "Messaging",
    "color": "#00B900",
    "description": "Japan's popular messaging app",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "KakaoTalk",
    "slug": "kakaotalk",
    "url": "https://www.kakaocorp.com/page/service/service/KakaoTalk",
    "category": "Messaging",
    "color": "#FFCD00",
    "description": "South Korea's messaging platform",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Viber",
    "slug": "viber",
    "url": "https://web.viber.com",
    "category": "Messaging",
    "color": "#7360F2",
    "description": "Free calls and messages",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "VK",
    "slug": "vk",
    "url": "https://vk.com/im",
    "category": "Social",
    "color": "#4C75A3",
    "description": "Russia's social network",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Twitch Chat",
    "slug": "twitch",
    "url": "https://www.twitch.tv",
    "category": "Entertainment",
    "color": "#9146FF",
    "description": "Live streaming chat",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Steam Chat",
    "slug": "steam-chat",
    "url": "https://steamcommunity.com/chat",
    "category": "Entertainment",
    "color": "#1B2838",
    "description": "Gaming community messages",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "GroupMe",
    "slug": "groupme",
    "url": "https://web.groupme.com",
    "category": "Messaging",
    "color": "#29ABE2",
    "description": "Group messaging platform",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Snapchat",
    "slug": "snapchat",
    "url": "https://web.snapchat.com",
    "category": "Social",
    "color": "#FFFC00",
    "description": "Disappearing photo messages",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Element (Matrix)",
    "slug": "element",
    "url": "https://app.element.io",
    "category": "Privacy",
    "color": "#0DBD8B",
    "description": "Decentralized secure messaging",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Google Voice",
    "slug": "google-voice",
    "url": "https://voice.google.com",
    "category": "Messaging",
    "color": "#34A853",
    "description": "Google phone calls and SMS",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "DingTalk",
    "slug": "dingtalk",
    "url": "https://www.dingtalk.com",
    "category": "Work",
    "color": "#1677FF",
    "description": "Alibaba's enterprise messaging",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Cisco Webex",
    "slug": "cisco-webex",
    "url": "https://web.webex.com",
    "category": "Work",
    "color": "#00BCEB",
    "description": "Enterprise video meetings",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Pushbullet",
    "slug": "pushbullet",
    "url": "https://www.pushbullet.com",
    "category": "Utility",
    "color": "#4AB367",
    "description": "Link devices and share content",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "XING",
    "slug": "xing",
    "url": "https://www.xing.com/messages",
    "category": "Social",
    "color": "#026466",
    "description": "European professional network",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Gitter",
    "slug": "gitter",
    "url": "https://app.gitter.im",
    "category": "Communities",
    "color": "#ED1965",
    "description": "Developer community chat",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Bluesky",
    "slug": "bluesky",
    "url": "https://bsky.app",
    "category": "Social",
    "color": "#0085ff",
    "description": "Decentralized social network with DMs.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Mastodon",
    "slug": "mastodon",
    "url": "https://mastodon.social",
    "category": "Social",
    "color": "#6364ff",
    "description": "Federated open-source social network.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Threads",
    "slug": "threads",
    "url": "https://www.threads.net",
    "category": "Social",
    "color": "#000000",
    "description": "Meta's text-based social platform.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Google Chat",
    "slug": "google-chat",
    "url": "https://chat.google.com",
    "category": "Work",
    "color": "#00ac47",
    "description": "Google Workspace team chat.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Workplace by Meta",
    "slug": "workplace",
    "url": "https://www.workplace.com",
    "category": "Work",
    "color": "#1877f2",
    "description": "Enterprise social network from Meta.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Twist",
    "slug": "twist",
    "url": "https://twist.com",
    "category": "Work",
    "color": "#ec6868",
    "description": "Async team communication by Doist.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Chanty",
    "slug": "chanty",
    "url": "https://app.chanty.com",
    "category": "Work",
    "color": "#fe5b3a",
    "description": "Simple team chat alternative.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Circle",
    "slug": "circle",
    "url": "https://app.circle.so",
    "category": "Communities",
    "color": "#4f46e5",
    "description": "Modern community platform for creators.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Geneva",
    "slug": "geneva",
    "url": "https://app.geneva.com",
    "category": "Communities",
    "color": "#ff4500",
    "description": "Group chats, rooms and clubs.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Yahoo Mail",
    "slug": "yahoo-mail",
    "url": "https://mail.yahoo.com",
    "category": "Email",
    "color": "#6001d2",
    "description": "Yahoo's classic webmail service.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Fastmail",
    "slug": "fastmail",
    "url": "https://app.fastmail.com",
    "category": "Email",
    "color": "#296dec",
    "description": "Privacy-respecting paid email service.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Tuta Mail",
    "slug": "tuta",
    "url": "https://app.tuta.com",
    "category": "Email",
    "color": "#840010",
    "description": "End-to-end encrypted email (Tutanota).",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Jitsi Meet",
    "slug": "jitsi",
    "url": "https://meet.jit.si",
    "category": "Video",
    "color": "#1d76ba",
    "description": "Free open-source video conferencing.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Whereby",
    "slug": "whereby",
    "url": "https://whereby.com/user",
    "category": "Video",
    "color": "#fe7e6d",
    "description": "Browser-based video meetings.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": false,
    "iframeNotes": "This platform blocks iframe embedding for security. It will open in a new browser tab instead."
  },
  {
    "name": "Session",
    "slug": "session",
    "url": "https://getsession.org",
    "category": "Privacy",
    "color": "#00f782",
    "description": "Anonymous decentralized messenger.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Tox",
    "slug": "tox",
    "url": "https://tox.chat",
    "category": "Privacy",
    "color": "#a72924",
    "description": "Peer-to-peer encrypted messaging.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Jami",
    "slug": "jami",
    "url": "https://jami.net",
    "category": "Privacy",
    "color": "#0067b9",
    "description": "Distributed peer-to-peer communication.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Briar",
    "slug": "briar",
    "url": "https://briarproject.org",
    "category": "Privacy",
    "color": "#001f3f",
    "description": "P2P encrypted messenger for activists.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Status",
    "slug": "status",
    "url": "https://status.im",
    "category": "Privacy",
    "color": "#4360df",
    "description": "Ethereum-based private messenger.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Meta Business Suite",
    "slug": "meta-business-suite",
    "url": "https://business.facebook.com/latest/inbox/chat",
    "category": "Work",
    "color": "#1877F2",
    "description": "Meta Business Suite messenger — manage customer conversations across Facebook, Instagram and Messenger in one inbox.",
    "iconUrl": null,
    "isPopular": false,
    "embedsInIframe": true,
    "iframeNotes": null
  },
  {
    "name": "Google Messages",
    "slug": "google-messages",
    "url": "https://messages.google.com/web",
    "category": "Messaging",
    "color": "#1a73e8",
    "description": "Text from your computer with Messages for web. Syncs with your Android phone.",
    "iconUrl": null,
    "isPopular": true,
    "embedsInIframe": true,
    "iframeNotes": null
  }
];
